# Generated by Django 5.0.8 on 2024-11-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
    ]
