# Generated by Django 5.0.8 on 2024-11-13 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_remove_resulttimetable_class_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resulttimetable',
            name='class_group_id',
        ),
        migrations.RemoveField(
            model_name='resulttimetable',
            name='classroom_id',
        ),
        migrations.RemoveField(
            model_name='resulttimetable',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='resulttimetable',
            name='instructor_id',
        ),
        migrations.RemoveField(
            model_name='resulttimetable',
            name='meeting_time_id',
        ),
        migrations.AddField(
            model_name='resulttimetable',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.resultclassgroup'),
        ),
        migrations.AddField(
            model_name='resulttimetable',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.resultclassroom'),
        ),
        migrations.AddField(
            model_name='resulttimetable',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.resultcourse'),
        ),
        migrations.AddField(
            model_name='resulttimetable',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.resultinstructor'),
        ),
        migrations.AddField(
            model_name='resulttimetable',
            name='meeting_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.resultmeetingtime'),
        ),
        migrations.AlterField(
            model_name='resultclassgroup',
            name='result_identification',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resultclassroom',
            name='result_identification',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resultcourse',
            name='result_identification',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resultinstructor',
            name='result_identification',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resultmeetingtime',
            name='result_identification',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resultprogram',
            name='result_identification',
            field=models.IntegerField(),
        ),
    ]
