# Generated by Django 5.0.8 on 2024-11-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_resulttimetable_result_identification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resulttimetable',
            name='class_group',
        ),
        migrations.RemoveField(
            model_name='resulttimetable',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='resulttimetable',
            name='course',
        ),
        migrations.RemoveField(
            model_name='resulttimetable',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='resulttimetable',
            name='meeting_time',
        ),
        migrations.AddField(
            model_name='resulttimetable',
            name='class_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resulttimetable',
            name='classroom_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resulttimetable',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resulttimetable',
            name='instructor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resulttimetable',
            name='meeting_time_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
