# Generated by Django 5.0.8 on 2024-11-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_alter_generatedschedule_result_identification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedschedule',
            name='json_file',
        ),
    ]
