# Generated by Django 5.0.8 on 2024-11-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_remove_generatedschedule_json_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialschedulerdata',
            name='task_record',
        ),
        migrations.DeleteModel(
            name='TaskRecord',
        ),
    ]
