# Generated by Django 5.0.8 on 2024-11-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20241115_0219'),
        ('timetable', '0011_remove_initialschedulerdata_task_record_and_more'),
    ]

    operations = [
    ]
