# Generated by Django 5.0.8 on 2024-11-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_merge_20241115_0223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periods',
            options={'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
        migrations.AlterModelOptions(
            name='weekday',
            options={'verbose_name': 'Weekday', 'verbose_name_plural': 'Weekdays'},
        ),
        migrations.AlterModelTable(
            name='periods',
            table='Periods',
        ),
        migrations.AlterModelTable(
            name='weekday',
            table='Weekday',
        ),
    ]
