# Generated by Django 5.0.8 on 2024-11-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0021_remove_resultprogram_class_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultprogram',
            name='courses',
        ),
    ]
