# Generated by Django 5.0.8 on 2024-11-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0026_resulttimetable_result_identification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resulttimetable',
            name='class_group_id',
        ),
        migrations.RemoveField(
            model_name='resulttimetable',
            name='classroom_id',
        ),
        migrations.RemoveField(
            model_name='resulttimetable',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='resulttimetable',
            name='instructor_id',
        ),
        migrations.RemoveField(
            model_name='resulttimetable',
            name='meeting_time_id',
        ),
    ]
