# Generated by Django 5.0.8 on 2024-11-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0029_resultschedule_timetable_r_result__649642_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultTimetable',
        ),
    ]
