# Generated by Django 5.0.8 on 2024-11-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0030_delete_resulttimetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultSchedule',
        ),
    ]
