# Generated by Django 5.0.8 on 2024-11-15 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0031_delete_resultschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTimetable',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.resultclassgroup')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.resultclassroom')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.resultcourse')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.resultinstructor')),
                ('meeting_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.resultmeetingtime')),
                ('result_identification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.resultidentification')),
            ],
            options={
                'verbose_name': 'Result Timetable',
                'verbose_name_plural': 'Result Timetables',
                'db_table': 'result_timetable',
                'indexes': [models.Index(fields=['result_identification'], name='result_time_result__78f77e_idx')],
            },
        ),
    ]
