# Generated by Django 5.0.8 on 2024-11-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0039_resulttimetable_class_group_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultprogram',
            name='program_id',
        ),
    ]
