# Generated by Django 5.0.8 on 2024-11-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0040_remove_resultprogram_program_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultprogram',
            name='program_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
