# Generated by Django 5.0.8 on 2024-11-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0041_resultprogram_program_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultclassroom',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resultclassroom',
            name='room_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultclassroom',
            name='room_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
