# Generated by Django 5.0.8 on 2024-11-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0045_alter_resultclassgroup_result_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultclassgroup',
            name='class_group_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultclassgroup',
            name='class_group_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultclassgroup',
            name='year_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
