# Generated by Django 5.0.8 on 2024-11-16 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0046_alter_resultclassgroup_class_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmeetingtime',
            name='credit_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultmeetingtime',
            name='meeting_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultmeetingtime',
            name='meeting_time',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultmeetingtime',
            name='result_identification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.resultidentification'),
            preserve_default=False,
        ),
    ]
