# Generated by Django 5.0.8 on 2024-11-16 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0047_alter_resultmeetingtime_credit_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultcourse',
            name='course_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultcourse',
            name='course_description',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultcourse',
            name='course_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultcourse',
            name='credit_units',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultcourse',
            name='lecture_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultcourse',
            name='result_identification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.resultidentification'),
            preserve_default=False,
        ),
    ]
