# Generated by Django 5.0.8 on 2024-11-16 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0049_alter_resulttimetable_result_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultinstructor',
            name='instructor_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultinstructor',
            name='instructor_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultinstructor',
            name='result_identification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.resultidentification'),
            preserve_default=False,
        ),
    ]
