# Generated by Django 5.0.8 on 2024-11-16 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0051_alter_generatedschedule_result_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultidentification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
