# Generated by Django 5.0.8 on 2024-11-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0056_alter_initialschedulerdata_result_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultcourse',
            name='lecture_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
