# Generated by Django 5.0.8 on 2024-11-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0057_alter_resultcourse_lecture_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultcourse',
            name='credit_units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
