# Generated by Django 5.0.8 on 2024-11-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0059_remove_resulttimetable_instructor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resulttimetable',
            name='instructor',
        ),
        migrations.AddField(
            model_name='resulttimetable',
            name='instructor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
