# Generated by Django 5.0.8 on 2024-11-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0062_alter_resultinstructor_instructor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttimetable',
            name='class_group_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resulttimetable',
            name='classroom_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resulttimetable',
            name='course_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resulttimetable',
            name='meeting_time_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resulttimetable',
            name='result_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
