# Generated by Django 5.0.8 on 2024-11-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0063_alter_resulttimetable_class_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttimetable',
            name='class_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resulttimetable',
            name='classroom_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resulttimetable',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resulttimetable',
            name='meeting_time_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resulttimetable',
            name='result_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
