# Generated by Django 5.0.8 on 2024-11-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0065_alter_resulttimetable_class_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultclassgroup',
            name='class_group_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultclassgroup',
            name='result_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultclassroom',
            name='result_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultclassroom',
            name='room_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultcourse',
            name='course_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultcourse',
            name='result_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultinstructor',
            name='result_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultmeetingtime',
            name='meeting_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultmeetingtime',
            name='result_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultprogram',
            name='program_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultprogram',
            name='result_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
