# Generated by Django 5.0.8 on 2024-11-17 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0068_remove_resultinstructor_instructor_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewtimetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='viewtimetable',
            name='result_identification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.resultidentification'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='viewtimetable',
            unique_together={('generated_schedule', 'share_to_instructor', 'user', 'result_identification')},
        ),
    ]
