# Generated by Django 5.0.8 on 2024-11-17 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0069_alter_viewtimetable_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewtimetable',
            unique_together={('share_to_instructor', 'user', 'result_identification')},
        ),
        migrations.AddIndex(
            model_name='viewtimetable',
            index=models.Index(fields=['result_identification'], name='view_timeta_result__15661f_idx'),
        ),
        migrations.RemoveField(
            model_name='viewtimetable',
            name='generated_schedule',
        ),
    ]
