# Generated by Django 5.0.8 on 2024-11-17 08:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0070_alter_viewtimetable_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewtimetable',
            unique_together={('user', 'result_identification')},
        ),
    ]
