# Generated by Django 5.0.8 on 2024-11-18 12:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0073_initialschedulerdata_initial_sch_result__cdb46b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resulttimetable',
            unique_together={('result_id', 'result_identification', 'instructor', 'class_group_id', 'course_id')},
        ),
    ]
