# Generated by Django 5.0.8 on 2024-11-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0077_alter_initialcourseassignment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InitialCourseAssignment',
        ),
    ]
