# Generated by Django 5.0.8 on 2024-11-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0079_initialcourseassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initialcourseassignment',
            old_name='instructor_id',
            new_name='instructor',
        ),
    ]
