# Generated by Django 5.0.8 on 2024-11-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0080_rename_instructor_id_initialcourseassignment_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialcourseassignment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
