# Generated by Django 5.0.8 on 2024-11-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0083_alter_resultclassgroup_result_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedschedule',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
