# Generated by Django 5.0.8 on 2024-11-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0085_alter_resultidentification_result_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialschedulerdata',
            name='scheduler_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
