# Generated by Django 5.0.8 on 2024-11-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0086_alter_initialschedulerdata_scheduler_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultcourse',
            name='year_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
