# Generated by Django 5.0.8 on 2024-11-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0087_resultcourse_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialcourseassignment',
            name='year_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
