# Generated by Django 5.0.8 on 2024-11-19 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0088_initialcourseassignment_year_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialcourseassignment',
            name='year_level',
        ),
    ]
