# Generated by Django 5.0.8 on 2024-11-19 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0039_courses_courses_course__bcfb55_idx_and_more'),
        ('timetable', '0091_alter_resultcourse_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultcourse',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.programs'),
        ),
    ]
