# Generated by Django 5.0.8 on 2024-11-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0092_alter_resultcourse_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmeetingtime',
            name='end_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resultmeetingtime',
            name='f2f_day',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resultmeetingtime',
            name='flexible_day',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resultmeetingtime',
            name='meeting_day',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resultmeetingtime',
            name='start_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resultmeetingtime',
            name='credit_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultmeetingtime',
            name='meeting_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
