# Generated by Django 5.0.8 on 2024-11-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0095_alter_generatedschedule_result_identification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initialcourseassignment',
            old_name='id',
            new_name='assignment_id',
        ),
    ]
