# Generated by Django 5.0.8 on 2024-11-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0097_alter_generatedschedule_total_generation_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedschedule',
            name='crossover_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedschedule',
            name='mutation_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedschedule',
            name='number_of_elite_schedule',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedschedule',
            name='number_of_generation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedschedule',
            name='population_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedschedule',
            name='tournament_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
