# Generated by Django 5.0.8 on 2024-11-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0098_generatedschedule_crossover_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedschedule',
            name='crossover_rate',
        ),
    ]
