# Generated by Django 5.0.8 on 2024-11-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0100_generatedschedule_early_mutate_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedschedule',
            old_name='early_mutate_rate',
            new_name='early_mutation_rate',
        ),
    ]
