# Generated by Django 5.0.8 on 2024-11-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0101_rename_early_mutate_rate_generatedschedule_early_mutation_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedschedule',
            name='early_mutation_rate',
        ),
    ]
