# Generated by Django 5.0.8 on 2024-11-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0104_alter_initialschedulerdata_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmeetingtime',
            name='meeting_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
