# Generated by Django 5.0.8 on 2024-11-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0033_alter_rooms_room_name'),
    ]

    operations = [
    ]
