# Generated by Django 5.0.8 on 2024-11-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0039_courses_courses_course__bcfb55_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_major_course',
            field=models.BooleanField(default=False),
        ),
    ]
