# Generated by Django 5.0.8 on 2025-01-07 08:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0040_courses_is_major_course'),
        ('institutes', '0003_institutes_institutes_institu_2f9a7d_idx'),
        ('user', '0042_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_rank', models.CharField(max_length=255)),
                ('undergraduate_degree', models.CharField(max_length=255)),
                ('graduate_degree', models.CharField(max_length=255)),
                ('employment_status', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('core_time', models.CharField(max_length=255)),
                ('student_consultation_time', models.CharField(max_length=255)),
                ('date_hired', models.DateField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.institutes')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.programs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
