# Generated by Django 5.0.8 on 2025-01-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_changepasswordotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangePasswordOTP',
        ),
    ]
