# Generated by Django 5.0.8 on 2025-01-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_delete_changepasswordotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='mark_as_read',
            field=models.BooleanField(default=False),
        ),
    ]
