# Generated by Django 5.0.8 on 2025-01-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_notification_mark_as_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='mark_as_read',
            new_name='is_read',
        ),
    ]
