# Generated by Django 5.0.8 on 2025-01-08 07:39

import apps.user.common.account_compress_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_rename_mark_as_read_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/108012025013034.jpg', upload_to='cover_image/'),
        ),
    ]
