# Generated by Django 5.0.8 on 2025-01-08 11:02

import apps.user.common.account_compress_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_alter_facultyprofile_academic_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='student_consultation_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/108012025013034.jpg', upload_to='cover_image/'),
        ),
    ]
