# Generated by Django 5.0.8 on 2025-01-09 08:30

import apps.user.common.account_compress_image
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0040_courses_is_major_course'),
        ('institutes', '0003_institutes_institutes_institu_2f9a7d_idx'),
        ('user', '0051_alter_facultyprofile_student_consultation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/108012025005640.jpg', upload_to='cover_image/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutes.institutes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.programs'),
        ),
    ]
