# Generated by Django 5.0.8 on 2025-01-09 09:21

import apps.user.common.account_compress_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_alter_user_cover_image_alter_user_institute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='employment_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Permanent'), (2, 'Temporary'), (3, 'Casual'), (4, 'Contract of Service'), (5, 'Job Order'), (6, 'Coterminous'), (7, 'Contractual')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/107012025225052.jpg', upload_to='cover_image/'),
        ),
    ]
