# Generated by Django 5.0.8 on 2025-01-23 00:37

import apps.user.common.account_compress_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_alter_user_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UndergraduateDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='graduate_degree',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='undergraduate_degree',
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/107012025225052.jpg', upload_to='cover_image/'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='graduate_degrees',
            field=models.ManyToManyField(blank=True, related_name='faculty_with_graduate', to='user.graduatedegree'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='undergraduate_degrees',
            field=models.ManyToManyField(blank=True, related_name='faculty_with_undergraduate', to='user.undergraduatedegree'),
        ),
    ]
