# Generated by Django 5.0.8 on 2025-02-01 06:24

import apps.user.common.account_compress_image
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_graduatedegree_undergraduatedegree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/1610112024235135.jpg', upload_to='cover_image/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.IntegerField(blank=True, choices=[(1, 'Instructor I'), (2, 'Instructor II'), (3, 'Instructor III'), (4, 'Assistant Professor I'), (5, 'Assistant Professor II'), (6, 'Assistant Professor III'), (7, 'Assistant Professor IV'), (8, 'Associate Professor I'), (9, 'Associate Professor II'), (10, 'Associate Professor III'), (11, 'Associate Professor IV'), (12, 'Associate Professor V'), (13, 'Professor I'), (14, 'Professor II'), (15, 'Professor III'), (16, 'Professor IV'), (17, 'Professor V'), (18, 'Professor VI'), (19, 'College Professor')], null=True),
        ),
        migrations.CreateModel(
            name='AdminLoadRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('hour', models.FloatField()),
                ('unit', models.FloatField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='REPLoadRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('hour', models.FloatField()),
                ('unit', models.FloatField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
