# Generated by Django 5.0.8 on 2025-02-05 14:01

import apps.user.common.account_compress_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_adminloadrelease_group_id_reploadrelease_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/107012025225205.jpg', upload_to='cover_image/'),
        ),
    ]
