# Generated by Django 5.0.8 on 2025-02-05 14:05

import apps.user.common.account_compress_image
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0040_courses_is_major_course'),
        ('user', '0059_alter_user_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminloadrelease',
            name='program_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curriculum.programs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reploadrelease',
            name='program_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curriculum.programs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/107012025225409.jpg', upload_to='cover_image/'),
        ),
        migrations.CreateModel(
            name='TeamTeach',
            fields=[
                ('team_teach_id', models.AutoField(primary_key=True, serialize=False)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
