# Generated by Django 5.0.8 on 2025-02-05 14:12

import apps.user.common.account_compress_image
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0040_courses_is_major_course'),
        ('user', '0060_adminloadrelease_program_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminloadrelease',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AlterField(
            model_name='adminloadrelease',
            name='program_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.programs'),
        ),
        migrations.AlterField(
            model_name='reploadrelease',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
        migrations.AlterField(
            model_name='reploadrelease',
            name='program_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.programs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/107012025225052.jpg', upload_to='cover_image/'),
        ),
    ]
