# Generated by Django 5.0.8 on 2025-02-05 14:50

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_alter_adminloadrelease_group_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltertMessage',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('show_again', models.BooleanField(default=True)),
                ('show_every_24_hours', models.DateTimeField(default=datetime.datetime(2025, 2, 6, 14, 50, 58, 756829, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
