# Generated by Django 5.0.8 on 2025-02-05 14:52

import apps.user.common.account_compress_image
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_altertmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altertmessage',
            name='show_every_24_hours',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 14, 52, 17, 437396, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/107012025225409.jpg', upload_to='cover_image/'),
        ),
    ]
