# Generated by Django 5.0.8 on 2025-02-05 14:52

import apps.user.common.account_compress_image
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0063_alter_altertmessage_show_every_24_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMessage',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('show_again', models.BooleanField(default=True)),
                ('show_every_24_hours', models.DateTimeField(default=datetime.datetime(2025, 2, 6, 14, 52, 41, 156664, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.DeleteModel(
            name='AltertMessage',
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/107012025225052.jpg', upload_to='cover_image/'),
        ),
        migrations.AddField(
            model_name='alertmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
