# Generated by Django 5.0.8 on 2025-02-06 15:50

import apps.user.common.account_compress_image
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0064_alertmessage_delete_altertmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmessage',
            name='show_every_24_hours',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 15, 50, 37, 933263, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/108012025013034.jpg', upload_to='cover_image/'),
        ),
    ]
