# Generated by Django 5.0.8 on 2025-02-06 15:52

import apps.user.common.account_compress_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0065_alter_alertmessage_show_every_24_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/107012025191346.jpg', upload_to='cover_image/'),
        ),
        migrations.DeleteModel(
            name='AlertMessage',
        ),
    ]
