# Generated by Django 5.0.8 on 2025-02-27 15:40

import apps.user.common.account_compress_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0066_alter_user_cover_image_delete_alertmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/107012025225409.jpg', upload_to='cover_image/'),
        ),
    ]
