# Generated by Django 5.0.8 on 2025-02-28 05:02

import apps.user.common.account_compress_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0067_alter_user_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=apps.user.common.account_compress_image.CoverImageField(default='cover_image/107012025225205.jpg', upload_to='cover_image/'),
        ),
    ]
