# Generated by Django 5.0.8 on 2024-11-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_alter_institutes_acronym_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='institutes',
            index=models.Index(fields=['institute_id'], name='institutes_institu_2f9a7d_idx'),
        ),
    ]
